# Generated by Django 6.1.1 on 2026-09-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_imagenadicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='JK Variedades', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Sube aquí tu logo (puedes cambiarlo en Navidad, amor y amistad, etc.)', null=True, upload_to='logo/')),
            ],
        ),
    ]
